# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0004_auto_20160116_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=100)),
                ('website_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_collection',
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('audio', 'שיר'), ('image', 'תמונה'), ('MAP', 'מפה'), ('TRV', 'יומן מסע'), ('VID', 'קטע וידאו'), ('OTR', 'אחר')], max_length=3, verbose_name='סוג התוכן'),
        ),
        migrations.AddField(
            model_name='content',
            name='collection',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='librarian.Collection', verbose_name='אוסף'),
            preserve_default=False,
        ),
    ]
