# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0005_auto_20160116_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('audio', 'שיר'), ('image', 'תמונה'), ('MAP', 'מפה'), ('TRV', 'יומן מסע'), ('VID', 'קטע וידאו'), ('OTR', 'אחר')], max_length=30, verbose_name='סוג התוכן'),
        ),
        migrations.AlterField(
            model_name='content',
            name='creator_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='יוצר/ת נוספ/ת'),
        ),
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='תאריך התוכן'),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=30, verbose_name='שם או כותרת'),
        ),
        migrations.AlterField(
            model_name='content',
            name='performing',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='מבצע/ת'),
        ),
    ]
