# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0006_auto_20160116_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='record_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='librarian.Collection', verbose_name='אוסף'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('audio', 'שיר'), ('image', 'תמונה'), ('archive', 'פריט ארכיון'), ('photograph', 'צילום'), ('MAP', 'מפה'), ('TRV', 'יומן מסע'), ('VID', 'קטע וידאו'), ('other', 'אחר')], max_length=30, verbose_name='סוג התוכן'),
        ),
    ]
