# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0007_auto_20160117_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('audio', 'שיר'), ('image', 'תמונה'), ('archive', 'פריט ארכיון'), ('photograph', 'צילום'), ('map', 'מפה'), ('TRV', 'יומן מסע'), ('VID', 'קטע וידאו'), ('sheet', 'גליון'), ('other', 'אחר')], max_length=30, verbose_name='סוג התוכן'),
        ),
    ]
