# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0008_auto_20160117_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='record_id',
            new_name='doc_id',
        ),
        migrations.AddField(
            model_name='content',
            name='full_record',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
